version: '3'
services:
  firefox_1:
    image: selenium/node-firefox-debug
    ports:
    - "5901:5900"
    volumes:
    - C:/docker:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  firefox_2:
    image: selenium/node-firefox-debug
    ports:
    - "5902:5900"    
    volumes:
    - C:/docker:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  firefox_3:
    image: selenium/node-firefox-debug
    ports:
    - "5903:5900"    
    depends_on:
      - hub
    volumes:
    - C:/docker:/dev/shm
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  mockserver:
    build:
      context: .
      dockerfile: dockerfile_create_mock_image
    environment:
    - PROXY_PORT=2023
    - SERVER_PORT=2033
    - APPLICATION_JAR=target/janusz.jar
    ports:
    - "2023:2023"
    - "2033:2033"
  wildflywithapp:
    build:
      context: .
      dockerfile: dockerfile_create_wildfly_server_and_deploy_app
      args:
        - APPLICATION_WAR=target/grazyna.war
    ports:
    - "8080:8080"